going through contortions to ignore SIGPIPE from gawk in awkcel and hawk

diff --git a/awkcel b/awkcel
--- a/awkcel
+++ b/awkcel
@@ -6,10 +6,11 @@
 
 die() { echo "$@" >&2; exit 1
 }
-
 newlines() { awk '{for(i=1; i<=NF; i++) print $i}' "$@"
 }
-
+NL='
+'
+TAB='	'
 case `uname` in
 Darwin) GSED=gsed;; # we need a sed that takes the "nu" option
 Linux)GSED=sed;;
@@ -71,4 +72,18 @@ fi
 ) > $TMPDIR/PROG
 
 
-gawk -F "$FIELD_SEP" -f $TMPDIR/PROG "$@"
+if gawk -F "$FIELD_SEP" -f $TMPDIR/PROG "$@"; then : # do nothing, just exit
+else
+    STATUS=$?
+    # egrep-like regular expression of exit status/signal names to ignore
+    IGNORE="PIPE"
+    # Automatically convert the names above to integers
+    if kill -l | fgrep -q "$TAB"; then # kill -l has the format "13) SIGPIPE", each separated by tabs
+	kill -l | tr "$TAB" "$NL"
+    else # kill -l has the format of space-separated "HUP INT QUIT", etc...
+	kill -l | newlines | grep -v IOT | nl   # but note IOT is a duplicate of TRAP--both are signal 6
+    fi | head -20 | egrep -i "$IGNORE" | awk '128+$1=='"$STATUS{good=1}END{exit !good}" && exit 0
+    echo "gawk failed with status $STATUS program file is in directory $TMPDIR/PROG" >&2
+    trap "" 0 1 2 3 15 # do not remove file
+    exit $STATUS
+fi
