added profiling and SetCopy

diff --git a/hawk b/hawk
--- a/hawk
+++ b/hawk
@@ -19,22 +19,32 @@ TMP=`mktemp /tmp/hawk.XXXXXX`
 
 DIR="`dirname $0`"
 TAB_CHAR=" " # space
-if [ "$1" = -T ]; then
-    TAB_CHAR="$TAB"; shift
-fi
+PROFILE= # set to the single letter p for profiling
+PROF_OUT=
+while true; do
+    case "$1" in
+    -T) TAB_CHAR="$TAB";;
+    -p*) PROFILE=p; PROF_OUT="$1";;
+    -*) die "unknown option '$1'";;
+    *) break;;
+    esac
+    shift
+done
+
 PROG="$1"
 shift
 
 echo "`cat "$DIR/misc.awk"`$PROG" > $TMP
 
-AWK=`(which gawk4 || which gawk) 2>/dev/null | head -1 | sed 's/\*//g'`
+AWK=`(which ${PROFILE}gawk4 || which ${PROFILE}gawk) 2>/dev/null | head -1 | sed 's/\*//g'`
 if [ -x "$AWK" ] && $AWK --version 2>/dev/null | fgrep 'GNU Awk 4.' >/dev/null; then
     :
 else
-    AWK=awk
+    AWK=${PROFILE}awk
 fi
+#echo '$AWK='"$AWK $PROF_OUT" >&2
 
-if $AWK -F "$TAB_CHAR" -f "$TMP" "$@"; then : # do nothing, just exit
+if $AWK $PROF_OUT -F "$TAB_CHAR" -f "$TMP" "$@"; then : # do nothing, just exit
 else
     STATUS=$?
     [ $STATUS -le 3 ] && exit $STATUS
@@ -45,8 +55,8 @@ else
 	kill -l | tr "$TAB" "$NL"
     else # kill -l has the format of space-separated "HUP INT QUIT", etc...
 	kill -l | newlines | grep -v IOT | nl   # but note IOT is a duplicate of TRAP--both are signal 6
-    fi | head -20 | egrep -i "$IGNORE" | $AWK '128+$1=='"$STATUS{good=1}END{exit !good}" && exit 0
-    echo "$AWK failed with status $STATUS program file is in file $TMP" >&2
+    fi | head -20 | egrep -i "$IGNORE" | awk '128+$1=='"$STATUS{good=1}END{exit !good}" && exit 0
+    echo "'$AWK $PROF_OUT' failed with status $STATUS program file is in file $TMP" >&2
     trap "" 0 1 2 3 15 # do not remove file
     exit $STATUS
 fi
